amplitude: 1.0
initial_frequency: 3.5e9
frequency_change_rate: 0.0
initial_phase: 0
num_samples: 10000000
#sample_rate: 1000.0
sample_rate: 24.04e6
output_iq_file: "output.fc32"
output_csv_file: "output.csv"
write_iq: false
write_csv: false
device_args: "type=b200"
tx_gain: 40
