amplitude: 1.0
initial_frequency: 10.0
frequency_change_rate: 0.1
initial_phase: 0.0
num_samples: 1000000
sample_rate: 1000.0
output_iq_file: "output.fc32"
output_csv_file: "output.csv"
write_iq: true
write_csv: true
