amplitude: 1.0
amplitude_width: 0.0
center_frequency: 0.0
bandwidth: 0
initial_phase: 10000000
sampling_freq: 40000000
num_samples: 10000
output_iq_file: "output.fc32"
output_csv_file: "output.csv"
write_iq: false
write_csv: false
device_args: "type=b200"
tx_gain: 40
