amplitude: 0.7
amplitude_width: 0.05
center_frequency: 3500e6
bandwidth: 1.0e7
initial_phase: 0
sampling_freq: 40e6
num_samples: 10737410
output_iq_file: "output.fc32"
output_csv_file: "output.csv"
write_iq: true
write_csv: false
device_args: "type=b200"
tx_gain: 40
